# Generated by Django 2.2.13 on 2020-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_auto_20200304_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralresponse',
            name='referral_url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
